### ISSUE TITLE
JSX value should be either an expression or a quoted JSX text

### ISSUE THREAD

**Issue by rawat1806** [BPouncey/ReactJS-ecommerce-template#27]
Hi, encountered the attached error in the Header component. 

ReactJS-ecommerce-template/src/components/header/header.component.jsx: JSX value should be either an expression or a quoted JSX text (45:22)
<img width="1013" alt="Screenshot 2021-12-07 at 5 45 47 AM" src="https://user-images.githubusercontent.com/46958490/144942961-512d668d-5152-47ae-afb8-9a9e137863f6.png">

**Comment by mohsin-sh** [comment]
Hey can I do this.

**Comment by bruceallday** [comment]
@mohsin-sh please feel free to open a PR
